{% set name = "openff-evaluator" %}
{% set version = "0.3.0" %}
{% set sha256 = "e71224e0f0dd3f85dade51ab909ed79f6a4ba1eb944a110f358bbc8f85fbb90a" %}

package:
  name: openff-evaluator
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - openforcefield >=0.4.1
    - numpy
    - pandas
    - openmm
    - networkx
    - pint >=0.10.1,<0.15
    - packmol
    - pymbar >=3.0.5
    - mdtraj >=1.9.3
    - dask >=2.7.0
    - distributed >=2.7.0
    - dask-jobqueue >=0.7.0
    - uncertainties
    - openmmtools
    - yank >=0.25.2
    - pyyaml
    - requests
    - rdkit
    - cmiles
    - python-dateutil
    - pydantic

test:
  imports:
    - openff.evaluator

about:
  home: https://github.com/openforcefield/openff-evaluator
  license: MIT
  license_file: LICENSE
  description: A physical property evaluation toolkit from the Open Forcefield Consortium.

extra:
  recipe-maintainers:
    - simonboothroyd
