{% set name = "openff-evaluator" %}
{% set version = "0.2.1" %}
#{% set sha256 = "c7f8b0d8d1026855a40a33388bb391929b109c40c2900748bc04dacb8ebc7294" %}

package:
  name: openff-evaluator
  version: {{ version }}

source:
#  url: https://github.com/openforcefield/{{ name }}/archive/v{{ version }}.tar.gz
#  sha256: {{ sha256 }}
  git_url: https://github.com/openforcefield/openff-evaluator.git
  git_tag: v{{ version }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - openforcefield >=0.4.1
    - numpy
    - pandas
    - openmm
    - networkx
    - pint >=0.10.1
    - packmol
    - pymbar >=3.0.5
    - mdtraj >=1.9.3
    - dask >=2.7.0
    - distributed >=2.7.0
    - dask-jobqueue >=0.7.0
    - uncertainties
    - openmmtools
    - yank >=0.24.1
    - pyyaml
    - requests
    - rdkit
    - cmiles
    - python-dateutil
    - pydantic

test:
  imports:
    - openff.evaluator

about:
  home: https://github.com/openforcefield/openff-evaluator
  license: MIT
  license_file: LICENSE
  description: A physical property evaluation toolkit from the Open Forcefield Consortium.

extra:
  recipe-maintainers:
    - simonboothroyd
